# 물고기 종류 별 대어 찾기

SELECT ID, FISH_NAME, LENGTH 
FROM FISH_INFO a JOIN FISH_NAME_INFO b
ON a.FISH_TYPE = b.FISH_TYPE
WHERE (a.FISH_TYPE, LENGTH) IN 
(SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH 
FROM FISH_INFO 
GROUP BY FISH_TYPE)
ORDER BY ID;